version: '3'

services:
  ngrok:
      image: ngrok/ngrok:latest
      restart: unless-stopped
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - ./ngrok.yml:/etc/ngrok.yml
      ports:
        - 4040:4040

  redis:
    image: redis:alpine
    ports:
      - "3106:6379"

  fbservice:
    container_name: fbservice
    depends_on:
      - redis
    build:
      context: ./src
    volumes:
      - ./src/data:/app/data
    ports:
      - "3105:3105"
